language: python
python:
  - 2.7
install: 
  - pip install -r requirements_dev.txt --use-mirrors
  - pip install coveralls
script: nosetests --with-coverage --cover-package address
after_success:
  coveralls
